"""add_error_message_to_images

Revision ID: b14d4b1f70d8
Revises: 812aac61b6bb
Create Date: 2026-05-28 23:35:05.347791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b14d4b1f70d8'
down_revision: Union[str, None] = '812aac61b6bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('error_message', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'error_message')
    # ### end Alembic commands ###
